/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*; 
import javax.swing.table.DefaultTableModel; 
import java.awt.*; 
import java.awt.event.ActionListener;
/**
 *
 * @author LENOVO
 */
public class PenjualanView extends javax.swing.JFrame {
    private final JTextField textKode, textNama, textHarga; 
    private final JTable table; 
    private final DefaultTableModel tableModel; 
    private final JButton btnSimpan, btnHapus; 
    /**
     * Creates new form PenjualanView
     */
    public PenjualanView() {
        initComponents();
        setTitle("Manajemen Data Penjualan"); 
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        setSize(600, 400); 
        setLayout(new BorderLayout()); 
 
        // Form Panel 
        JPanel panelForm = new JPanel(new GridLayout(4, 2)); 
        panelForm.add(new JLabel("Kode:")); 
        textKode = new JTextField(); 
        panelForm.add(textKode); 
 
        panelForm.add(new JLabel("Nama:")); 
        textNama = new JTextField(); 
        panelForm.add(textNama); 
 
        panelForm.add(new JLabel("Harga:")); 
        textHarga = new JTextField(); 
        panelForm.add(textHarga); 
 
        btnSimpan = new JButton("Simpan"); 
        btnHapus = new JButton("Hapus"); 
        panelForm.add(btnSimpan); 
        panelForm.add(btnHapus); 
 
        // Tabel 
        tableModel = new DefaultTableModel(new String[]{"Kode", "Nama", 
"Harga"}, 0); 
        table = new JTable(tableModel); 
        JScrollPane scrollPane = new JScrollPane(table); 
 
        add(panelForm, BorderLayout.NORTH); 
        add(scrollPane, BorderLayout.CENTER); 
 
        setVisible(true); 
    }
    // Getter 
    public JTextField getTextKode() { return textKode; } 
    public JTextField getTextNama() { return textNama; } 
    public JTextField getTextHarga() { return textHarga; } 
    public JButton getBtnSimpan() { return btnSimpan; } 
    public JButton getBtnHapus() { return btnHapus; } 
    public JTable getTable() { return table; } 
    public DefaultTableModel getTableModel() { return tableModel; } 
 
    // Listener 
    public void addSimpanListener(ActionListener listener) { 
        btnSimpan.addActionListener(listener); 
    } 
    
    public void addHapusListener(ActionListener listener) { 
        btnHapus.addActionListener(listener); 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
