/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.BorderLayout; 
import javax.swing.JButton; 
import javax.swing.JFrame; 
import javax.swing.SwingUtilities;
/**
 *
 * @author LENOVO
 */
public class BorderLayoutDemo extends javax.swing.JFrame {

    /**
     * Creates new form BorderLayoutDemo
     */
    public BorderLayoutDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        JFrame frame = new JFrame("Contoh Border Layout"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(400, 200); 
        frame.setLayout(new BorderLayout(5, 5)); // Mengatur jarak antar komponen 
 
        // Membuat tombol di se ap posisi 
        JButton btnNorth = new JButton("Posisi NORTH"); 
        JButton btnSouth = new JButton("Posisi SOUTH"); 
        JButton btnEast = new JButton("Posisi EAST"); 
        JButton btnWest = new JButton("Posisi WEST"); 
        JButton btnCenter = new JButton("Posisi CENTER"); 
         
        // Menambahkan tombol ke frame sesuai posisi 
        frame.add(btnNorth, BorderLayout.NORTH); 
        frame.add(btnSouth, BorderLayout.SOUTH); 
        frame.add(btnEast, BorderLayout.EAST); 
        frame.add(btnWest, BorderLayout.WEST); 
        frame.add(btnCenter, BorderLayout.CENTER); 
        frame.setVisible(true); 
        }); 
        } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
