/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.FlowLayout; 
import javax.swing.JButton; 
import javax.swing.JFrame; 
import javax.swing.JLabel; 
import javax.swing.SwingUtilities;
/**
 *
 * @author LENOVO
 */
public class ButtonEventDemo extends javax.swing.JFrame {

    /**
     * Creates new form ButtonEventDemo
     */
    public ButtonEventDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        JFrame frame = new JFrame("Button"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(300, 150); 
        frame.setLayout(new FlowLayout(FlowLayout.CENTER)); 
        JLabel label = new JLabel("Warna Yang Dipilih : "); 
        JLabel labelWarna = new JLabel(""); 
        JButton btnMerah = new JButton("Merah"); 
        JButton btnBiru = new JButton("Biru"); 
        btnMerah.addActionListener(e -> labelWarna.setText("Merah")); 
        btnBiru.addActionListener(e -> labelWarna.setText("Biru")); 
        frame.add(btnMerah); 
        frame.add(btnBiru); 
        frame.add(label); 
        frame.add(labelWarna); 
        frame.setVisible(true); 
        }); 
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
