/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.FlowLayout; 
import javax.swing.JButton; 
import javax.swing.JCheckBox; 
import javax.swing.JFrame; 
import javax.swing.JLabel; 
import javax.swing.JOptionPane; 
import javax.swing.SwingUtilities;
/**
 *
 * @author LENOVO
 */
public class CheckBoxEventDemo extends javax.swing.JFrame {

    /**
     * Creates new form CheckBoxEventDemo
     */
    public CheckBoxEventDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        JFrame frame = new JFrame("Checkbox"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(400, 150); 
        frame.setLayout(new FlowLayout()); 
        JLabel label = new JLabel("Media Sosial Yang Dimiliki"); 
        JCheckBox cbFacebook = new JCheckBox("Facebook"); 
        JCheckBox cbTwitter = new JCheckBox("Twitter"); 
        JCheckBox cbInstagram = new JCheckBox("Instagram"); 
        JCheckBox cbLine = new JCheckBox("Line"); 
        JButton btnTampilkan = new JButton("Tampilkan"); 
        btnTampilkan.addActionListener(e -> { 
        StringBuilder hasil = new StringBuilder("Anda memiliki: "); 
        if (cbFacebook.isSelected()) hasil.append("Facebook "); 
        if (cbTwitter.isSelected()) hasil.append("Twitter "); 
        if (cbInstagram.isSelected()) hasil.append("Instagram "); 
        if (cbLine.isSelected()) hasil.append("Line "); 
        JOptionPane.showMessageDialog(frame, hasil.toString()); 
        }); 
        frame.add(label); 
        frame.add(cbFacebook); 
        frame.add(cbTwitter); 
        frame.add(cbInstagram); 
        frame.add(cbLine); 
        frame.add(btnTampilkan); 
        frame.setVisible(true); 
        }); 
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
