/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.FlowLayout; 
import javax.swing.JButton; 
import javax.swing.JComboBox; 
import javax.swing.JFrame; 
import javax.swing.JLabel; 
import javax.swing.JOptionPane; 
import javax.swing.SwingUtilities; 
/**
 *
 * @author LENOVO
 */
public class ComboBoxEventDemo extends javax.swing.JFrame {

    /**
     * Creates new form ComboBoxEventDemo
     */
    public ComboBoxEventDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        JFrame frame = new JFrame("ComboBox"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(300, 100); 
        frame.setLayout(new FlowLayout()); 
        JLabel label = new JLabel("Fakultas : "); 
        String[] fakultas = {"FIF", "FKB", "FIT", "FEB", "FTE", "FRI", "FIK"}; 
        JComboBox<String> comboBox = new JComboBox<>(fakultas); 
        JButton btnTampilkan = new JButton("Tampilkan"); 
        btnTampilkan.addActionListener(e -> { 
        JOptionPane.showMessageDialog(frame, "Fakultas yang dipilih: " + 
        comboBox.getSelectedItem()); 
        }); 
        frame.add(label); 
        frame.add(comboBox); 
        frame.add(btnTampilkan); 
        frame.setVisible(true); 
        }); 
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
