/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.FlowLayout; 
import javax.swing.ButtonGroup; 
import javax.swing.JButton; 
import javax.swing.JFrame; 
import javax.swing.JLabel; 
import javax.swing.JOptionPane; 
import javax.swing.JRadioButton; 
import javax.swing.SwingUtilities; 
/**
 *
 * @author LENOVO
 */
public class RadioButtonEventDemo extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonEventDemo
     */
    public RadioButtonEventDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
    SwingUtilities.invokeLater(() -> { 
    JFrame frame = new JFrame("Radio Bu on"); 
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
    frame.setSize(400, 100); 
    frame.setLayout(new FlowLayout()); 
    JLabel label = new JLabel("Jenis Kelamin : "); 
    JRadioButton rbLaki = new JRadioButton("Laki-Laki"); 
    JRadioButton rbPerempuan = new JRadioButton("Perempuan"); 
    ButtonGroup group = new ButtonGroup(); 
    group.add(rbLaki); 
    group.add(rbPerempuan); 
    JButton btnTampilkan = new JButton("Tampilkan"); 
    btnTampilkan.addActionListener(e -> { 
    String pilihan = rbLaki.isSelected() ? "Laki-Laki" : 
    rbPerempuan.isSelected() ? "Perempuan" : "Tidak ada yang dipilih"; 
    JOptionPane.showMessageDialog(frame, "Anda memilih: " + pilihan); 
    }); 
    frame.add(label); 
    frame.add(rbLaki); 
    frame.add(rbPerempuan); 
    frame.add(btnTampilkan); 
    frame.setVisible(true); 
    }); 
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
