/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.FlowLayout; 
import javax.swing.JButton; 
import javax.swing.JFrame; 
import javax.swing.JLabel; 
import javax.swing.JScrollPane; 
import javax.swing.JTable; 
import javax.swing.JTextField; 
import javax.swing.SwingUtilities; 
import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author LENOVO
 */
public class TableEventDemo extends javax.swing.JFrame {

    /**
     * Creates new form TableEventDemo
     */
    public TableEventDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        JFrame frame = new JFrame("Tabel"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(400, 250); 
        frame.setLayout(new FlowLayout()); 
        JLabel labelNama = new JLabel("Nama : "); 
        JTextField textNama = new JTextField(15); 
        JLabel labelGender = new JLabel("Jenis Kelamin : "); 
        JTextField textGender = new JTextField(15); 
        DefaultTableModel model = new DefaultTableModel(new String[]{"Nama", 
        "Jenis Kelamin"}, 0); 
        JTable table = new JTable(model); 
        JScrollPane scrollPane = new JScrollPane(table); 
        JButton btnSimpan = new JButton("Simpan"); 
        JButton btnHapus = new JButton("Hapus"); 
        JButton btnClear = new JButton("Clear"); 
        btnSimpan.addActionListener(e -> model.addRow(new 
        Object[]{textNama.getText(), textGender.getText()})); 
        btnHapus.addActionListener(e -> 
        model.removeRow(table.getSelectedRow())); 
        btnClear.addActionListener(e -> model.setRowCount(0)); 
        frame.add(labelNama); 
        frame.add(textNama); 
        frame.add(labelGender); 
        frame.add(textGender); 
        frame.add(btnSimpan); 
        frame.add(btnHapus); 
        frame.add(btnClear); 
        frame.add(scrollPane); 
        frame.setVisible(true); 
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
