/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.CardLayout; 
import javax.swing.JButton; 
import javax.swing.JFrame; 
import javax.swing.JLabel; 
import javax.swing.JPanel; 
import javax.swing.JTextField; 
import javax.swing.SwingUtilities;
/**
 *
 * @author LENOVO
 */
public class CardLayoutDemo extends javax.swing.JFrame {

    /**
     * Creates new form CardLayoutDemo
     */
    public CardLayoutDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        // Membuat frame utama 
        JFrame frame = new JFrame("CardLayout Demo"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(300, 200); 
        // Membuat panel utama dengan CardLayout 
        JPanel cardPanel = new JPanel(); 
        CardLayout cardLayout = new CardLayout(); 
        cardPanel.setLayout(cardLayout); 
        // Panel pertama dengan tombol 
        JPanel panel1 = new JPanel(); 
        JButton btnNext = new JButton("Ke Panel 2"); 
        panel1.add(new JButton("Tombol 1")); 
        panel1.add(new JButton("Tombol 2")); 
        panel1.add(btnNext); 
        // Panel kedua dengan TextField 
        JPanel panel2 = new JPanel(); 
        JTextField textField = new JTextField(15); 
        JButton btnBack = new JButton("Kembali"); 
        panel2.add(new JLabel("Masukkan Teks:")); 
        panel2.add(textField); 
        panel2.add(btnBack); 
        // Menambahkan panel ke CardLayout 
        cardPanel.add(panel1, "Panel 1"); 
        cardPanel.add(panel2, "Panel 2"); 
        // Menambahkan aksi untuk berpindah panel 
        btnNext.addActionListener(e -> cardLayout.show(cardPanel, "Panel 2")); 
        btnBack.addActionListener(e -> cardLayout.show(cardPanel, "Panel 1")); 
        // Menambahkan CardLayout ke frame 
        frame.add(cardPanel); 
        frame.setVisible(true); 
        }); 
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
