/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jdialogexample;
import java.awt.FlowLayout; 
import javax.swing.JButton; 
import javax.swing.JFrame; 
import javax.swing.JPanel; 
import javax.swing.SwingUtilities; 
/**
 *
 * @author LENOVO
 */
public class FlowLayoutDemo extends javax.swing.JFrame {

    /**
     * Creates new form FlowLayoutDemo
     */
    public FlowLayoutDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { 
        SwingUtilities.invokeLater(() -> { 
        // Membuat frame utama 
        JFrame frame = new JFrame("FlowLayout Demo"); 
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        frame.setSize(350, 200); 
        //komponen 
        // Mengatur layout menjadi FlowLayout dengan rata kiri dan jarak antar 
        FlowLayout layout = new FlowLayout(FlowLayout.LEFT, 10, 20); 
        JPanel panel = new JPanel(); 
        panel.setLayout(layout); 
        // Menambahkan tombol ke dalam panel 
        JButton btn1 = new JButton("Button 1"); 
        JButton btn2 = new JButton("Button 2"); 
        JButton btn3 = new JButton("Button 3"); 
        JButton btn4 = new JButton("Long-Named Bu on 4"); 
        JButton btn5 = new JButton("Button 5"); 
        panel.add(btn1); 
        panel.add(btn2); 
        panel.add(btn3); 
        panel.add(btn4); 
        panel.add(btn5); 
        // Menambahkan panel ke dalam frame 
        frame.add(panel); 
        frame.setVisible(true); 
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
